// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBySUpCbpmiSbTNiEIVLAu70LlQJH-nkKY',
    appId: '1:921013274197:web:33acd3f801cfb223a136dc',
    messagingSenderId: '921013274197',
    projectId: 'quiz-app-flutter-a070b',
    authDomain: 'quiz-app-flutter-a070b.firebaseapp.com',
    storageBucket: 'quiz-app-flutter-a070b.firebasestorage.app',
    measurementId: 'G-DGFDVQ53RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBySUpCbpmiSbTNiEIVLAu70LlQJH-nkKY',
    appId: '1:921013274197:android:your-android-app-id',
    messagingSenderId: '921013274197',
    projectId: 'quiz-app-flutter-a070b',
    storageBucket: 'quiz-app-flutter-a070b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBySUpCbpmiSbTNiEIVLAu70LlQJH-nkKY',
    appId: '1:921013274197:ios:your-ios-app-id',
    messagingSenderId: '921013274197',
    projectId: 'quiz-app-flutter-a070b',
    storageBucket: 'quiz-app-flutter-a070b.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBySUpCbpmiSbTNiEIVLAu70LlQJH-nkKY',
    appId: '1:921013274197:ios:your-macos-app-id',
    messagingSenderId: '921013274197',
    projectId: 'quiz-app-flutter-a070b',
    storageBucket: 'quiz-app-flutter-a070b.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );
}
